"""Industry case-study presets.

Each entry is a fully-specified ``SystemConfig`` that the UI loads to populate every
control at once. Presets are modeled **per satellite** (one tile of a constellation);
fleet economics scale by the number of satellites. Numbers are illustrative starting
points tuned to land KPIs in plausible aerospace ranges -- not vendor quotes.
"""

from __future__ import annotations

from models import SystemConfig

SUNCATCHER = SystemConfig(
    name="Google Project Suncatcher",
    # Hyperscale TPU constellation, dawn-dusk SSO ~650 km, optimized mass production,
    # Starship-class launch. Modeled as one ~1 MW node of a larger fleet.
    num_racks=8,
    power_per_rack_kW=120.0,
    gpus_per_rack=64,
    parasitic_overhead_fraction=0.10,
    panel_efficiency=0.32,
    illumination_fraction=0.99,
    solar_areal_density_kg_m2=1.5,
    radiator_emissivity=0.90,
    T_sink_K=3.0,
    T_surface_max_K=318.0,
    radiator_sides=2,
    radiator_width_m=8.0,
    radiator_areal_density_kg_m2=6.0,
    rack_mass_kg=850.0,
    structural_mass_multiplier=1.4,
    enable_degradation=True,
    annual_degradation_pct=0.02,
    launch_cost_per_kg=200.0,
    altitude_km=650.0,
    lifespan_years=10,
    rack_unit_cost=2_500_000.0,
    space_qualification_premium=1.4,
    solar_cost_per_m2=250.0,
    radiator_cost_per_m2=800.0,
    rd_integration_overhead_pct=0.15,
    ground_station_cost_annual=800_000.0,
    stationkeeping_cost_annual=300_000.0,
    insurance_pct_of_hardware=0.05,
    terrestrial_ops_cost_annual=700_000.0,
    revenue_mode="per_gpu_hour",
    revenue_per_gpu_hour=2.20,
    utilization=0.90,
    discount_rate=0.10,
    grid_cost_per_kWh=0.06,
    pue=1.2,
    terrestrial_land_cost_annual=200_000.0,
    terrestrial_water_cost_annual=100_000.0,
    terrestrial_ground_ops_annual=500_000.0,
    terrestrial_capex_per_MW=10_000_000.0,
)

STARCLOUD = SystemConfig(
    name="Starcloud",
    # SmallSat clusters of Nvidia H100/B200-class GPUs. High launch cost offset by premium
    # sovereign / edge / inference billing rates.
    num_racks=4,
    power_per_rack_kW=50.0,
    gpus_per_rack=72,
    parasitic_overhead_fraction=0.12,
    panel_efficiency=0.30,
    illumination_fraction=0.95,
    solar_areal_density_kg_m2=2.0,
    radiator_emissivity=0.90,
    T_sink_K=3.0,
    T_surface_max_K=318.0,
    radiator_sides=2,
    radiator_width_m=6.0,
    radiator_areal_density_kg_m2=8.0,
    rack_mass_kg=900.0,
    structural_mass_multiplier=1.6,
    enable_degradation=True,
    annual_degradation_pct=0.03,
    launch_cost_per_kg=1500.0,
    altitude_km=550.0,
    lifespan_years=7,
    rack_unit_cost=2_500_000.0,
    space_qualification_premium=1.6,
    solar_cost_per_m2=400.0,
    radiator_cost_per_m2=1_200.0,
    rd_integration_overhead_pct=0.20,
    ground_station_cost_annual=1_000_000.0,
    stationkeeping_cost_annual=500_000.0,
    insurance_pct_of_hardware=0.06,
    terrestrial_ops_cost_annual=1_000_000.0,
    revenue_mode="per_gpu_hour",
    revenue_per_gpu_hour=6.00,
    utilization=0.85,
    discount_rate=0.12,
    grid_cost_per_kWh=0.08,
    pue=1.3,
    terrestrial_land_cost_annual=250_000.0,
    terrestrial_water_cost_annual=150_000.0,
    terrestrial_ground_ops_annual=600_000.0,
    terrestrial_capex_per_MW=12_000_000.0,
)

FIRST_PRINCIPLES_RACK_SAT = SystemConfig(
    name="First-Principles Rack-Sat",
    # Monolithic deployment: 1 satellite = 1-3 full server racks paired with massive
    # deployed radiators (300-400 ft) to balance extreme AI-chip thermal density.
    num_racks=2,
    power_per_rack_kW=150.0,
    gpus_per_rack=64,
    parasitic_overhead_fraction=0.10,
    panel_efficiency=0.29,
    illumination_fraction=0.98,
    solar_areal_density_kg_m2=2.0,
    radiator_emissivity=0.90,
    T_sink_K=3.0,
    T_surface_max_K=318.0,
    radiator_sides=2,
    radiator_width_m=3.0,
    radiator_areal_density_kg_m2=10.0,
    rack_mass_kg=1000.0,
    structural_mass_multiplier=1.7,
    enable_degradation=True,
    annual_degradation_pct=0.025,
    launch_cost_per_kg=500.0,
    altitude_km=600.0,
    lifespan_years=10,
    rack_unit_cost=3_500_000.0,
    space_qualification_premium=1.8,
    solar_cost_per_m2=350.0,
    radiator_cost_per_m2=1_500.0,
    rd_integration_overhead_pct=0.30,
    ground_station_cost_annual=600_000.0,
    stationkeeping_cost_annual=400_000.0,
    insurance_pct_of_hardware=0.07,
    terrestrial_ops_cost_annual=500_000.0,
    revenue_mode="per_gpu_hour",
    revenue_per_gpu_hour=3.00,
    utilization=0.88,
    discount_rate=0.10,
    grid_cost_per_kWh=0.07,
    pue=1.25,
    terrestrial_land_cost_annual=200_000.0,
    terrestrial_water_cost_annual=100_000.0,
    terrestrial_ground_ops_annual=500_000.0,
    terrestrial_capex_per_MW=10_000_000.0,
)

PRESETS: dict[str, SystemConfig] = {
    SUNCATCHER.name: SUNCATCHER,
    STARCLOUD.name: STARCLOUD,
    FIRST_PRINCIPLES_RACK_SAT.name: FIRST_PRINCIPLES_RACK_SAT,
}
